import { z } from 'zod'

/**
 * Shared Zod schema for soil/crop diagnosis JSON returned by Gemini (vision + JSON mode).
 */
export const diagnosisResultSchema = z.object({
  summary: z.string(),
  likelyIssues: z
    .array(
      z.object({
        name: z.string(),
        confidence: z.enum(['low', 'medium', 'high']),
        evidence: z.string(),
      })
    )
    .default([]),
  unlikelyButSerious: z.array(z.string()).optional().default([]),
  recommendedActions: z
    .array(
      z.object({
        title: z.string(),
        detail: z.string(),
      })
    )
    .default([]),
  needsMoreInfo: z.array(z.string()).optional().default([]),
  safetyNotes: z.string().optional().default(''),
})

export const DIAGNOSIS_DISCLAIMER =
  'This assessment is generated by AI from photographs only. It is not a laboratory soil test or a certified agronomic inspection. Always confirm critical decisions with a qualified local agronomist and follow product label laws in your jurisdiction.'

/** System-style rules for the diagnosis LLM */
export const DIAGNOSIS_SYSTEM_PROMPT = `You are a cautious agricultural assistant helping smallholder farmers (including South Asia / Bangladesh context when relevant).
Rules:
- You only see images and short text notes — state uncertainty clearly.
- Never claim certainty for disease ID from photos alone; prefer "possible" language.
- Prefer cultural and IPM steps before suggesting chemicals; if you mention pesticides/fertilizers, stress label directions and local regulations.
- Output a single JSON object only, no markdown fences, matching exactly this shape:
{"summary":string,"likelyIssues":[{"name":string,"confidence":"low"|"medium"|"high","evidence":string}],"unlikelyButSerious":[string],"recommendedActions":[{"title":string,"detail":string}],"needsMoreInfo":[string],"safetyNotes":string}
- likelyIssues: 0–5 items. recommendedActions: 1–8 practical steps.
- If images are unclear, say so in summary and needsMoreInfo.`

/**
 * @param {unknown} parsed
 * @returns {{ result: object }}
 */
export function assertDiagnosisShape(parsed) {
  const parsedResult = diagnosisResultSchema.safeParse(parsed)
  if (!parsedResult.success) {
    const err = new Error('Model JSON did not match expected schema')
    err.statusCode = 502
    err.data = parsedResult.error.flatten()
    throw err
  }
  return { result: parsedResult.data }
}
