import { GoogleGenerativeAI } from '@google/generative-ai'
import { z } from 'zod'
import { env } from '../config/env.js'

const MAX_ATTEMPTS = 3

const SYSTEM_PROMPT = `You are an expert agricultural advisor helping smallholder farmers choose the best crops for their land.
Rules:
- Consider local climate, soil type, season, and crop rotation principles.
- Prefer sustainable and low-input methods where appropriate.
- Recommend 2–5 suitable crops with clear reasoning.
- Output a single JSON object only, no markdown fences, matching exactly this shape:
{"recommendedCrops":[{"name":string,"reasoning":string,"careNotes":string}],"rotationAdvice":string,"seasonalTips":string,"generalNotes":string}
- recommendedCrops: 2–5 items. Be specific and practical.`

export const RECOMMENDATION_DISCLAIMER =
  'This recommendation is generated by AI and is for informational purposes only. Always consult a qualified local agronomist before making major cropping decisions.'

const recommendationSchema = z.object({
  recommendedCrops: z
    .array(
      z.object({
        name: z.string(),
        reasoning: z.string(),
        careNotes: z.string(),
      })
    )
    .min(1)
    .max(5),
  rotationAdvice: z.string().default(''),
  seasonalTips: z.string().default(''),
  generalNotes: z.string().default(''),
})

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

function retryDelayMs(error, attempt) {
  const msg = String(error?.message || '')
  const m = msg.match(/please retry in ([\d.]+)\s*s\b/i)
  if (m) {
    const sec = parseFloat(m[1])
    if (!Number.isNaN(sec) && sec > 0) return Math.min(90_000, Math.ceil(sec * 1000) + 250)
  }
  return Math.min(20_000, 1000 * 2 ** attempt + Math.random() * 400)
}

function shouldRetry(e) {
  const msg = String(e?.message || '').toLowerCase()
  return (
    msg.includes('resource_exhausted') ||
    msg.includes('429') ||
    msg.includes('too many requests') ||
    msg.includes('quota exceeded')
  )
}

/**
 * Generate crop recommendations via Google Gemini (text-only).
 *
 * @param {object} params
 * @param {string} [params.cropType]    current or desired crop
 * @param {string} [params.soilType]
 * @param {string} [params.region]
 * @param {string} [params.season]
 * @param {string} [params.notes]       extra farmer context
 * @param {string} [params.landContext] pre-formatted land info
 * @returns {Promise<{ result: object, disclaimer: string, model: string }>}
 */
export async function runRecommendation({
  cropType = '',
  soilType = '',
  region = '',
  season = '',
  notes = '',
  landContext = '',
}) {
  if (!env.geminiApiKey) {
    const err = new Error('Gemini is not configured')
    err.statusCode = 503
    err.hint = 'Set GEMINI_API_KEY in server/.env (from https://aistudio.google.com/apikey ).'
    throw err
  }

  const genAI = new GoogleGenerativeAI(env.geminiApiKey)
  const modelName = env.geminiChatModel

  const model = genAI.getGenerativeModel({
    model: modelName,
    systemInstruction: SYSTEM_PROMPT,
    generationConfig: {
      temperature: 0.4,
      responseMimeType: 'application/json',
    },
  })

  const contextLines = [
    cropType && `Current/desired crop: ${cropType}`,
    soilType && `Soil type: ${soilType}`,
    region && `Region/location: ${region}`,
    season && `Season: ${season}`,
    landContext && `Land details: ${landContext}`,
    notes && `Farmer notes: ${notes}`,
  ].filter(Boolean)

  const prompt =
    contextLines.length > 0
      ? `Based on the following context, recommend the best crops for this land:\n\n${contextLines.join('\n')}\n\nReply with JSON only as instructed.`
      : 'Recommend suitable crops for a smallholder farm in South Asia. Reply with JSON only as instructed.'

  let lastErr = null
  for (let attempt = 0; attempt < MAX_ATTEMPTS; attempt++) {
    try {
      const res = await model.generateContent(prompt)
      const text = res.response.text().trim()

      let parsed
      try {
        parsed = JSON.parse(text)
      } catch {
        const match = text.match(/\{[\s\S]*\}/)
        if (!match) {
          const err = new Error('Model returned non-JSON output')
          err.statusCode = 502
          throw err
        }
        parsed = JSON.parse(match[0])
      }

      const validated = recommendationSchema.safeParse(parsed)
      if (!validated.success) {
        const err = new Error('Model JSON did not match expected schema')
        err.statusCode = 502
        err.data = validated.error.flatten()
        throw err
      }

      return { result: validated.data, disclaimer: RECOMMENDATION_DISCLAIMER, model: modelName }
    } catch (e) {
      lastErr = e
      if (shouldRetry(e) && attempt < MAX_ATTEMPTS - 1) {
        await sleep(retryDelayMs(e, attempt))
        continue
      }
      break
    }
  }

  const err = lastErr instanceof Error ? lastErr : new Error('Gemini request failed')
  if (!err.statusCode) err.statusCode = 502
  throw err
}
